app/app/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("api/", include("statistics_api.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]


handler404 = "app.views.page_not_found_view"
handler500 = "app.views.server_error_view"

app/users/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.RegisterUserView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_reset/", views.CustomPasswordResetView.as_view(), name="password_reset"),
    path("", include("django.contrib.auth.urls")),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("token/", views.GetToken.as_view(), name="get_token"),
    path("create_payment/", views.PaymentView.as_view(), name="payment"),
    path("payment_webhook/", views.payment_webhook, name="payment_webhook"),
    path("open_customer_portal/", views.open_customer_portal, name="open_customer_portal"),
    path("payment_success/", views.PaymentSuccess.as_view(), name="payment_success"),
    path("payment_failed/", views.PaymentFailed.as_view(), name="payment_failed"),
]

app/users/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager
from django.db import models
from django.db.models import Case
from django.db.models import Count
from django.db.models import F
from django.db.models import Value
from django.db.models import When
from django.db.models.functions import Coalesce
from django.utils.translation import gettext_lazy as _


class UserManager(UserManager):
    def with_requests_left(self):
        return self.annotate(
            requests_left=Coalesce(F("membershiplevels__membership_level__requests_number"), Value(50))
            - Count(Case(When(requestlogs__countable=True, requestlogs__created__date=datetime.date.today(), then=1)))
        )


class User(AbstractUser):
    birthday = models.DateField(null=True)
    updated = models.DateTimeField(auto_now=True)
    email = models.EmailField(_("email address"), blank=True, unique=True)
    username = None
    customer_id = models.CharField(null=True)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    objects = UserManager()


class MembershipLevel(models.Model):
    type = models.CharField(null=False)
    requests_number = models.IntegerField(null=False)
    stripe_plan_id = models.CharField(null=False)


class RequestLog(models.Model):
    user = models.ForeignKey(User, related_name="requestlogs", on_delete=models.SET_NULL, null=True)
    url = models.CharField(null=False)
    countable = models.BooleanField(null=False)
    created = models.DateTimeField(auto_now_add=True)


class UserMembershipLevel(models.Model):
    user = models.ForeignKey(User, related_name="membershiplevels", on_delete=models.CASCADE)
    membership_level = models.ForeignKey(MembershipLevel, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    ended = models.DateTimeField(null=True, default=None)


class Token(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    deleted = models.DateTimeField(null=True, default=None)

app/users/utils/models.py
from django.db.models import ImageField
from django.forms import forms
from django.template.defaultfilters import filesizeformat
from django.utils.translation import gettext_lazy as _


class SizeRestrictedImageField(ImageField):
    """
    Same as ImageField, but you can specify:
          max_upload_size - a number indicating the maximum file size allowed for upload.
            2.5MB - 2621440
            5MB - 5242880
            10MB - 10485760
            20MB - 20971520
            50MB - 5242880
            100MB - 104857600
            250MB - 214958080
            500MB - 429916160
    """

    def __init__(self, *args, **kwargs):
        self.max_upload_size = kwargs.pop("max_upload_size", 0)

        super(SizeRestrictedImageField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        data = super(SizeRestrictedImageField, self).clean(*args, **kwargs)

        image = data.file
        if image.size > self.max_upload_size:
            raise forms.ValidationError(
                _("Please keep filesize under %s. Current filesize %s")
                % (filesizeformat(self.max_upload_size), filesizeformat(image.size))
            )

        return data


def group_moderator_create(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="moderator")

app/users/forms.py
from datetime import date

from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django_countries.widgets import CountrySelectWidget

from .models import MembershipLevel
from .models import User
from .utils.constants import MINIMUM_DATE_OF_BIRTH
from .utils.general import email_authenticate


class UserCreationForm(forms.ModelForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=256,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    birthday = forms.DateField()

    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    error_messages = {
        "password_mismatch": _("The two password fields didn’t match."),
    }

    first_name = forms.CharField(required=True)

    last_name = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "birthday")
        widgets = {"country": CountrySelectWidget()}

    def clean_email(self):
        email = self.cleaned_data.get("email")
        email_exists = User.objects.filter(email=email).first()
        if email_exists:
            msg = "This email is already exist"
            self.add_error("email", msg)
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                self.error_messages["password_mismatch"],
                code="password_mismatch",
            )
        return password2

    def clean_birthday(self):
        birthday = self.cleaned_data.get("birthday")
        if birthday > date.today() or birthday < MINIMUM_DATE_OF_BIRTH:
            msg = "Incorrect date"
            self.add_error("birthday", msg)

        return birthday

    def save(self, commit=True):
        instance = super(UserCreationForm, self).save(commit=False)
        instance.set_password(self.cleaned_data["password1"])
        if commit:
            instance.save()
        return instance


class LoginForm(forms.Form):
    email = forms.EmailField(
        label=_("Email"),
        max_length=256,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    password = forms.CharField(
        widget=forms.PasswordInput,
        error_messages={"required": "Please Enter your password"},
    )

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            user = email_authenticate(email=email, password=password)
            if user is None:
                raise ValidationError("incorrect email or password")
        return self.cleaned_data


class TariffPlanForm(forms.Form):
    queryset = MembershipLevel.objects.all()

    CHOICES = {(x.stripe_plan_id, f"{x.type} {x.requests_number}") for x in queryset}

    choices = forms.ChoiceField(
        choices=CHOICES,
        widget=forms.RadioSelect,
    )

app/users/views.py
# from django.conf import settings
# from django.contrib.auth import authenticate
import datetime

import stripe
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetView
from django.http import HttpRequest
from django.http import HttpResponse
from django.http import HttpResponseRedirect

# from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect

from .forms import LoginForm
from .forms import TariffPlanForm
from .forms import UserCreationForm
from .models import Token
from .models import UserMembershipLevel
from .tasks import create_stripe_customer
from .tasks import distribution_task
from .utils.general import CustomPasswordResetForm
from .utils.general import email_authenticate
from .utils.token import JWT

User = get_user_model()


class RegisterUserView(View):
    template_name = "registration/register.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {"form": UserCreationForm}
        return render(request, self.template_name, context)

    @method_decorator(csrf_protect)
    def post(self, request: HttpRequest) -> HttpResponseRedirect | HttpResponse:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            password = form.cleaned_data.get("password1")
            email = form.cleaned_data.get("email")
            user = email_authenticate(email=email, password=password)
            result = create_stripe_customer.delay(email)
            stripe_customer_id = result.get()
            user.customer_id = stripe_customer_id
            user.save()
            login(request, user)
            return redirect("home")
        context = {"form": form}
        return render(request, self.template_name, context)


class ProfileView(LoginRequiredMixin, View):
    template_name = "users/profile.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {"form": AuthenticationForm}
        return render(request, self.template_name, context)


class LoginView(View):
    template_name = "registration/login.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {"form": LoginForm}
        return render(request, self.template_name, context)

    @method_decorator(csrf_protect)
    def post(self, request: HttpRequest) -> HttpResponseRedirect | HttpResponse:
        form = LoginForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get("password")
            email = form.cleaned_data.get("email")
            user = email_authenticate(email=email, password=password)
            login(request, user)
            return redirect("home")
        context = {"form": form}
        return render(request, self.template_name, context)


class CustomPasswordResetView(PasswordResetView):
    email_template_name = "emails/password_reset_email.html"
    success_url = reverse_lazy("users:password_reset_done")
    form_class = CustomPasswordResetForm


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy("users:password_reset_complete")


class GetToken(LoginRequiredMixin, View):
    template_name = "users/token.html"

    def post(self, request: HttpRequest) -> HttpResponse:
        user = User.objects.get(id=request.user.id)
        old_token = Token.objects.filter(user__id=request.user.id, deleted=None).first()
        if old_token:
            old_token.deleted = datetime.datetime.now(datetime.timezone.utc)
            old_token.save()

        token = Token.objects.create(user=user, deleted=None)
        payload = {
            "user_id": user.id,
            "token_id": token.id,
        }

        token = JWT.encode(
            payload,
        )
        context = {"token": token, "is_token_exist": True}
        return render(request, self.template_name, context)

    def get(self, request: HttpRequest) -> HttpResponse:
        is_token_exist = Token.objects.filter(user__id=request.user.id, deleted=None).exists()
        context = {"is_token_exist": is_token_exist}
        return render(request, self.template_name, context)


@csrf_exempt
def payment_webhook(request):
    payload = request.body
    sig_header = request.META["HTTP_STRIPE_SIGNATURE"]
    endpoint_secret = "whsec_mcZ8y9DQeLM73aQ5hnPuwqiNrlfBbdu6"

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, endpoint_secret)

    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    distribution_task.delay(event_type=event.type, payload=payload)
    return HttpResponse(status=200)


def open_customer_portal(request: HttpRequest):
    customer = stripe.Customer.retrieve(request.user.customer_id)
    portal_session = stripe.billing_portal.Session.create(customer=customer.id, return_url="http://127.0.0.1:8000/")
    return redirect(portal_session.url)


class PaymentView(LoginRequiredMixin, View):
    template_name = "users/result_template.html"
    success_url = "users/payment_success"
    cancel_url = "users/payment_failed"

    def get(self, request):
        form = TariffPlanForm()
        subscription = UserMembershipLevel.objects.filter(user=request.user, ended__isnull=True).first()
        if subscription is None:
            subscriber = False
        else:
            subscriber = True
        return render(request, self.template_name, {"form": form, "subscriber": subscriber})

    def post(self, request):
        form = TariffPlanForm(request.POST)
        if form.is_valid():
            selected_choice = form.cleaned_data["choices"]

            product = stripe.Product.retrieve(selected_choice)
            prices = stripe.Price.list(product=product)

            checkout_session = stripe.checkout.Session.create(
                payment_method_types=["card"],
                line_items=[
                    {
                        "price": prices["data"][0].id,
                        "quantity": 1,
                    },
                ],
                mode="subscription",
                customer=request.user.customer_id,
                success_url=f"http://{request.get_host()}/{self.success_url}",
                cancel_url=f"http://{request.get_host()}/{self.cancel_url}",
            )

            return redirect(checkout_session.url, code=303)

        else:
            return render(request, self.template_name, {"form": form})


class PaymentSuccess(View):
    template_name = "users/payment_success.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, self.template_name)


class PaymentFailed(View):
    template_name = "users/payment_failed.html"

    def get(self, request: HttpRequest) -> HttpResponse:
        return render(request, self.template_name)

app/templates/users/payment_failed.html
{% extends 'base.html' %}
{% block title %}
Payment
{% endblock %}
{% block content %}



    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">

    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #D9534F;  /* Цвет для неудачи */
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #D9534F;  /* Цвет для иконки неудачи */
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>

      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✖️</i>  <!-- Заменено на крестик -->
      </div>
        <h1>Payment Failed</h1>  <!-- Заголовок изменен -->
        <p>We encountered an issue with your payment;<br/> please try again later!</p>  <!-- Сообщение изменено -->
      </div>




{% endblock %}

app/templates/users/payment_success.html
{% extends 'base.html' %}
{% block title %}
Payment
{% endblock %}
{% block content %}


<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">

    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>

      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We received your purchase request;<br/> we'll be in touch shortly!</p>
      </div>



{% endblock %}

app/templates/users/profile.html
{% extends 'base.html' %}
{% block title %}
Profile
{% endblock %}
{% block content %}

<section style="background-color: #eee;">
    <div class="container py-5">

        <div class="row">

            <div class="col-lg-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.first_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Surname</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.last_name}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.email}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Date of Birth</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{user.birthday}}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Date of Registration</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.date_joined }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Token</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><a href="{% url 'users:get_token' %}">Token managment</a></p>
                            </div>
                        </div>
                        
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Subscribe</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0"><a href="{% url 'users:payment' %}">Subscribe managment</a></p>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

app/templates/users/result_template.html
{% extends 'base.html' %}
{% block title %}
Payment
{% endblock %}
{% block content %}

<div class="container">

    <div class="row g-5">
  
      <div class="col-sm-8">
        <br>
        <div class="d-flex align-items-center">

            <div class="ms-3">
              <h3 class="mb-0 text-inherit">Subscription Managment</h3>

            </div>
          </div>
        <div class="card-body">

            <div class="mt-5"></div>
                {%if not subscriber%}

                <form method="POST">
                    {% csrf_token %}

                    <div class="list-group">

                    {% for choice in form.choices %}
                    <div class="list-group-item list-group-item-action"
                        aria-current="true">
                        {{choice}}
                    </div>
                    {% endfor %}

                    </div>


                </div>

                <div class="mt-3 d-flex justify-content-between">
                
                <button class="btn btn-primary" type="submit">Submit</button>
                
                </div>
                </form>

                {%else%}
                you have now active subscription, to update details move to                       
                        <a href="{% url 'users:open_customer_portal' %}">Link</a>


                {%endif%}
            </div>

        </div>

    </div>

</div>

</div>
{% endblock %}

app/templates/users/token.html
{% extends 'base.html' %}
{% block title %}
Token
{% endblock %}
{% block content %}

<style>
    .text-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
        border: 1px solid #ccc;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 10px;
    }
    .text-content {
        flex: 1;
    }
    .button-container {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
</style>

<form method="post">
    {% csrf_token %}
    <div class="container mt-4">
        <div class="text-container">
            <div class="text-content">
                <p class="text-break" id="tokenText">{{token}}</p>
            </div>
            <button type="button" class="copy-button btn btn-secondary" onclick="copyText()">Copy</button>
        </div>

        <div class="button-container">
            <button class="btn btn-primary" type="submit">{% if is_token_exist %}update token{% else %}create token{% endif %}</button>
        </div>
    </div>
</form>


<script>
    function copyText() {
        var text = document.getElementById("tokenText");
        var selection = window.getSelection();
        var range = document.createRange();
        range.selectNodeContents(text);
        selection.removeAllRanges();
        selection.addRange(range);
        document.execCommand("copy");
    }
</script>

{% endblock %}