app/app/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("api/", include("statistics_api.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]


handler404 = "app.views.page_not_found_view"
handler500 = "app.views.server_error_view"

app/users/urls.py
from django.urls import include
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path("signup/", views.RegisterUserView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("password_reset/", views.CustomPasswordResetView.as_view(), name="password_reset"),
    path("", include("django.contrib.auth.urls")),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("token/", views.GetToken.as_view(), name="get_token"),
    path("create_payment/", views.PaymentView.as_view(), name="payment"),
    path("payment_webhook/", views.payment_webhook, name="payment_webhook"),
    path("open_customer_portal/", views.open_customer_portal, name="open_customer_portal"),
    path("payment_success/", views.PaymentSuccess.as_view(), name="payment_success"),
    path("payment_failed/", views.PaymentFailed.as_view(), name="payment_failed"),
]

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/style.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body class="d-flex flex-column h-100">
    

    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/' %}active{% endif %}"
                                href="{% url 'home' %}">Home</a>
                        </li>

                        <li class="end-0 nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Account
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarScrollingDropdown">
                                {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'users:profile' %}">{{ user.email }}</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'users:login' %}">Login</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:signup' %}">Registration</a></li>
                                {% endif %}
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="flex-shrink-0 before-space">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <footer class="footer mt-auto py-3 bg-body-tertiary">
        <div class="container">
            <span class="text-body-secondary">Place sticky footer content here.</span>
        </div>
    </footer>


</body>

</html>

app/templates/home.html
{% extends 'base.html' %}
{% block title %}
Home page
{% endblock %}
{% block content %}
<h1>Home page</h1>
<hr>
{% endblock %}